# Generated by Django 2.2.7 on 2020-01-30 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_auto_20191114_0818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='terminatedemployees',
            name='employee',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='termination_report', serialize=False, to='users.Employee'),
        ),
    ]
