# Generated by Django 2.2 on 2020-03-17 22:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='received',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
