services:
  db:
    image: mysql:8.0
    platform: linux/amd64
    restart: always
    command: mysqld --default-authentication-plugin=mysql_native_password
    ports:
      - '3306:3306'
    env_file:
      - .env
    environment:
      - MYSQL_DATABASE=${SQL_DATABASE}
      - MYSQL_USER=${SQL_USER}
      - MYSQL_PASSWORD=${SQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${SQL_ROOT_PASSWORD}
    volumes:
      - mysql:/var/lib/mysql

  web:
    build:
      context: .
    platform: linux/amd64
    image: &hr_system hr_system
    ports:
      - "8000:8000"
    volumes:
      - .:/hr_system
    command: python manage.py runserver 0.0.0.0:8000
    env_file: &environ_file
      - .env
    depends_on:
      - db
      - rabbitmq
      - celery_worker
    links:
      - db

  celery_worker:
    build: .
    image: *hr_system
    platform: linux/amd64
    env_file: *environ_file
    command: celery -A hr_system worker --loglevel=info -E --uid=celery
    volumes:
      - .:/hr_system
    depends_on:
      - rabbitmq
      - db

  rabbitmq:
    platform: linux/amd64
    image: rabbitmq:3.7-alpine
    env_file: *environ_file
    ports:
      - "15672:15672"

  memcached:
    image: memcached:alpine
    ports:
      - "11211:11211"

volumes:
    mysql: