version: "3"

services:
  db:
    image: mysql:5.7
    ports:
      - '13306:3306'
    environment:
      MYSQL_DATABASE: 'payroll_schema'
      MYSQL_USER: 'payroll'
      MYSQL_PASSWORD: 'Kam12345'
      MYSQL_ROOT_PASSWORD: "Kam12345"
    volumes:
      - dbdata:/var/lib/mysql

  web:
    build:
      context: .
    image: &hr_system hr_system
    ports:
      - "8000:8000"
      - "3306:3306"
    volumes:
      - .:/hr_system
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"
    env_file: &environ_file
      - .env
    depends_on:
      - db
      - rabbitmq
      - celery_worker

  celery_worker:
    build: .
    image: *hr_system
    env_file: *environ_file
    command: celery -A hr_system worker --loglevel=info -E --uid=celery
    volumes:
      - .:/hr_system
    depends_on:
      - rabbitmq
      - db

  rabbitmq:
    image: rabbitmq:3.7-alpine
    env_file: *environ_file
    ports:
      - "15672:15672"

volumes:
  dbdata: