# Generated by Django 2.2.7 on 2020-02-04 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExTraSummaryReportInfo',
            fields=[
                ('key', models.CharField(blank=True, default=None, max_length=150, primary_key=True, serialize=False, unique=True)),
                ('analysis', models.CharField(blank=True, max_length=150, null=True)),
                ('employee_name', models.CharField(blank=True, max_length=250, null=True)),
                ('job_title', models.CharField(blank=True, max_length=150, null=True)),
                ('total_deductions', models.DecimalField(decimal_places=2, default=None, max_digits=12)),
                ('net_pay', models.DecimalField(decimal_places=2, default=None, max_digits=12)),
                ('gross_earning', models.DecimalField(decimal_places=2, default=None, max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='NSSFReport',
            fields=[
                ('report_key', models.CharField(blank=True, default=None, max_length=150, primary_key=True, serialize=False, unique=True)),
                ('employee_id', models.IntegerField()),
                ('agresso_number', models.CharField(blank=True, max_length=30, null=True)),
                ('nsif_or_nssf_number', models.CharField(blank=True, max_length=30, null=True)),
                ('employee_full_name', models.CharField(blank=True, max_length=300, null=True)),
                ('duty_station', models.CharField(blank=True, max_length=100, null=True)),
                ('cost_centre', models.CharField(blank=True, max_length=30, null=True)),
                ('job_title', models.CharField(blank=True, max_length=150, null=True)),
            ],
        ),
    ]
