# Generated by Django 2.2 on 2020-03-06 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reports', '0001_initial'),
        ('users', '0001_initial'),
        ('payroll', '0002_auto_20200306_0938'),
    ]

    operations = [
        migrations.AddField(
            model_name='nssfreport',
            name='earnings_and_deductions',
            field=models.ManyToManyField(blank=True, to='users.PayrollProcessors'),
        ),
        migrations.AddField(
            model_name='nssfreport',
            name='payroll_period',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='payroll.PayrollPeriod'),
        ),
        migrations.AddField(
            model_name='nssfreport',
            name='user_extra_report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reports.ExTraSummaryReportInfo'),
        ),
        migrations.AddField(
            model_name='extrasummaryreportinfo',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='report', to='users.Employee'),
        ),
        migrations.AddField(
            model_name='extrasummaryreportinfo',
            name='payroll_period',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='payroll.PayrollPeriod'),
        ),
    ]
