# Generated by Django 2.2 on 2020-03-06 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_auto_20200306_0938'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NSSFReport',
        ),
    ]
