# Generated by Django 2.2 on 2020-03-12 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_auto_20200130_1122'),
        ('reports', '0003_auto_20200310_0929'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extrasummaryreportinfo',
            name='earnings',
        ),
        migrations.RemoveField(
            model_name='taxationreport',
            name='gross_pay',
        ),
        migrations.AddField(
            model_name='extrasummaryreportinfo',
            name='deductions_to_display',
            field=models.ManyToManyField(related_name='deductions', to='users.PayrollProcessors'),
        ),
        migrations.AddField(
            model_name='extrasummaryreportinfo',
            name='earnings_to_display',
            field=models.ManyToManyField(related_name='earnings', to='users.PayrollProcessors'),
        ),
        migrations.AddField(
            model_name='taxationreport',
            name='summary_report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reports.ExTraSummaryReportInfo'),
        ),
        migrations.DeleteModel(
            name='BankReport',
        ),
    ]
