# Generated by Django 2.2 on 2020-03-06 10:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('payroll', '0002_auto_20200306_0938'),
        ('reports', '0003_delete_nssfreport'),
    ]

    operations = [
        migrations.CreateModel(
            name='NSSFReport',
            fields=[
                ('report_key', models.CharField(blank=True, default=None, max_length=150, primary_key=True, serialize=False, unique=True)),
                ('employee_id', models.IntegerField()),
                ('agresso_number', models.CharField(blank=True, max_length=30, null=True)),
                ('nsif_or_nssf_number', models.CharField(blank=True, max_length=30, null=True)),
                ('employee_full_name', models.CharField(blank=True, max_length=300, null=True)),
                ('duty_station', models.CharField(blank=True, max_length=100, null=True)),
                ('cost_centre', models.CharField(blank=True, max_length=30, null=True)),
                ('job_title', models.CharField(blank=True, max_length=150, null=True)),
                ('earnings_and_deductions', models.ManyToManyField(blank=True, to='users.PayrollProcessors')),
                ('payroll_period', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='payroll.PayrollPeriod')),
                ('user_extra_report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reports.ExTraSummaryReportInfo')),
            ],
        ),
    ]
