# Generated by Django 2.2 on 2020-03-12 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_auto_20200312_1034'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_id', models.CharField(editable=False, max_length=50)),
                ('period', models.CharField(blank=True, max_length=15, null=True)),
                ('staff_full_name', models.CharField(blank=True, max_length=200, null=True)),
                ('payment_location', models.CharField(blank=True, max_length=200, null=True)),
                ('bank', models.CharField(blank=True, max_length=200, null=True)),
                ('branch', models.CharField(blank=True, max_length=150, null=True)),
                ('sort_code', models.CharField(blank=True, max_length=15, null=True)),
                ('account_number', models.CharField(blank=True, max_length=30, null=True)),
                ('summary_report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reports.ExTraSummaryReportInfo')),
            ],
        ),
    ]
