# Generated by Django 2.2.7 on 2020-04-23 23:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0006_auto_20200316_0729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extrasummaryreportinfo',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='report', to='users.Employee'),
        ),
    ]
