# Generated by Django 2.2.7 on 2020-02-04 16:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('support_data', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payroll', '0002_auto_20200204_1620'),
    ]

    operations = [
        migrations.AddField(
            model_name='payrollapprover',
            name='approver',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='organization',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='support_data.Country'),
        ),
        migrations.AddField(
            model_name='dutystation',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='support_data.Country'),
        ),
        migrations.AddField(
            model_name='dutystation',
            name='earnings_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='payroll.EarningDeductionType'),
        ),
    ]
