# Generated by Django 2.2 on 2020-02-20 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support_data', '0003_auto_20200108_1049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sudanesetaxrates',
            name='actual_usd',
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='sudanesetaxrates',
            name='actual_usd_taxable_amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='sudanesetaxrates',
            name='lower_ssp_bound',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='sudanesetaxrates',
            name='upper_ssp_bound',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
