# Generated by Django 5.0.8 on 2024-08-12 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support_data', '0004_auto_20200220_0655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tax',
            name='year',
            field=models.IntegerField(choices=[(2024, 2024), (2025, 2025), (2026, 2026), (2027, 2027), (2028, 2028), (2029, 2029), (2030, 2030), (2031, 2031), (2032, 2032), (2033, 2033)], default=2024),
        ),
    ]
